import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import './LogicGateShader'; // Registers 'mHDMaterial'

const PlasmaTopology = ({ 
  systemLoad = 0.1,    // 0.0 - 1.0 (Turbulence)
  clockSpeed = 1.0,    // Solar Wind sync (Alfven Speed)
  radius = 2.5 
}) => {
  const materialRef = useRef();
  const meshRef = useRef();

  // Smooth state transitions (Laminar -> Turbulent)
  // We do not want instant jumps in viscosity; physics takes time to react.
  const currentTurbulence = useRef(0);

  useFrame((state, delta) => {
    if (materialRef.current) {
      // 1. Update Global Time
      materialRef.current.uTime += delta;

      // 2. Lerp Turbulence for physical weight (Simulating fluid inertia)
      currentTurbulence.current = THREE.MathUtils.lerp(
        currentTurbulence.current,
        systemLoad,
        delta * 2.0 // Viscosity factor
      );
      
      materialRef.current.uTurbulence = currentTurbulence.current;
      materialRef.current.uAlfvenSpeed = clockSpeed;
    }
    
    // 3. Slow axial rotation (Coriolis effect approximation)
    if (meshRef.current) {
      meshRef.current.rotation.y += delta * 0.05;
    }
  });

  return (
    <mesh ref={meshRef}>
      <sphereGeometry args={[radius, 128, 128]} />
      {/* mHDMaterial is generated by `shaderMaterial` and `extend` 
        in the previous file.
      */}
      <mHDMaterial 
        ref={materialRef} 
        transparent={false}
      />
    </mesh>
  );
};

export default PlasmaTopology;
